/* Ejecutar estas sentencias si ya tienen las tabals creadas */
DROP TABLE cat_doc;
DROP TABLE categoria;
DROP TABLE matricula;
DROP TABLE curso;
DROP TABLE alumno;
DROP TABLE materia;
DROP TABLE carrera;
DROP TABLE profesor;
DROP TABLE libro;

-- Ejecutar desde acá si no tienen las tablas creadas 


CREATE TABLE ALUMNO  (
    legajo   NUMBER(4, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    apellido VARCHAR2(40 BYTE)  NOT NULL, 
	nombre VARCHAR2(40 BYTE) NOT NULL, 
	fecha_nacimiento DATE, 
	mail VARCHAR2(45 BYTE) , 
	carrera NUMBER(4,0)
);

INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Albarran','Maximiliano',TO_DATE('12/10/1991','DD/MM/RRRR'),'malbarran702@alumnos.frh.utn.edu.ar',4);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Catalano','Francisco Joaquin',TO_DATE('02/12/1975','DD/MM/RRRR'),'fcatalano653@alumnos.frh.utn.edu.ar',3);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Lawaisse','Lisandro',TO_DATE('07/09/1998','DD/MM/RRRR'),'llawaisse804@alumnos.frh.utn.edu.ar',1);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Ponce','Paola Natalia',TO_DATE('03/01/1991','DD/MM/RRRR'),'pponce746@alumnos.frh.utn.edu.ar',5);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Yedro','Fernando Sebastian',TO_DATE('17/04/1987','DD/MM/RRRR'),'fyedro776@alumnos.frh.utn.edu.ar',2);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Boiveau','Ignacio',TO_DATE('06/12/1976','DD/MM/RRRR'),'iboiveau792@alumnos.frh.utn.edu.ar',4);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Bruzzese','Ignacio',TO_DATE('12/09/1984','DD/MM/RRRR'),'ibruzzese815@alumnos.frh.utn.edu.ar',1);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Esquer','Natalin',TO_DATE('03/07/2001','DD/MM/RRRR'),'nesquer778@alumnos.frh.utn.edu.ar',3);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Grande','Lautaro',TO_DATE('01/10/1998','DD/MM/RRRR'),'lgrande773@alumnos.frh.utn.edu.ar',3);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Ibarrola Portillo','Mathias Fernando',TO_DATE('04/02/1992','DD/MM/RRRR'),'mibarrola793@alumnos.frh.utn.edu.ar',1);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Martinez','Juan Segundo',TO_DATE('09/12/1999','DD/MM/RRRR'),'jmartinez784@alumnos.frh.utn.edu.ar',1);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Melotta','Gabriel',TO_DATE('11/01/2001','DD/MM/RRRR'),'gmelotta953@alumnos.frh.utn.edu.ar',1);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Ponce','Viviana Sofia',TO_DATE('03/01/1991','DD/MM/RRRR'),'vponce811@alumnos.frh.utn.edu.ar',5);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Kolque Cardoso','Antonella Belen',TO_DATE('18/09/1987','DD/MM/RRRR'),'akolque799@alumnos.frh.utn.edu.ar',2);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Giudice','Vilma',TO_DATE('16/07/2000','DD/MM/RRRR'),'vgiudice@nolose.com',2);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Perez','Luisa',TO_DATE('1/12/2000','DD/MM/RRRR'),'lperez@nolose.com',2);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Garcia','Irene',TO_DATE('6/03/2000','DD/MM/RRRR'),'igarcia@nolose.com',2);
INSERT INTO alumno (apellido,nombre,fecha_nacimiento,mail,carrera) VALUES ('Rodriguez','Juan Jose',TO_DATE('26/08/2001','DD/MM/RRRR'),'jrodrigueze@nolose.com',1);

CREATE TABLE carrera (
	id NUMBER(4,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	nombre VARCHAR2(40 BYTE) NOT NULL 
);

INSERT INTO carrera (nombre) VALUES ('INGENIERIA INDUSTRIAL');
INSERT INTO carrera (nombre) VALUES ('INGENIERIA AERONAUTICA');
INSERT INTO carrera (nombre) VALUES ('INGENIERIA EN SISTEMAS');
INSERT INTO carrera (nombre) Values ('INGENIERIA CIVICA');
INSERT INTO carrera (nombre) Values ('INGENIERIA QUIMICA');
INSERT INTO carrera (nombre) Values ('INGENIERIA QUIMICA');

ALTER TABLE alumno ADD FOREIGN KEY (carrera) REFERENCES carrera(id);

CREATE TABLE materia (
	id NUMBER(4,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	nombre VARCHAR2(35 BYTE)  NOT NULL 
);

INSERT INTO materia (nombre) VALUES ('ANALISIS MATEMATICO I');
INSERT INTO materia (nombre) VALUES ('ANALISIS MATEMATICO II');
INSERT INTO materia (nombre) VALUES ('QUIMICA ORGANICA');
INSERT INTO materia (nombre) VALUES ('QUIMICA INORGANICA');
INSERT INTO materia (nombre) VALUES ('FISICA I');
INSERT INTO materia (nombre) VALUES ('FISICA II');
INSERT INTO materia (nombre) VALUES ('FISICA III');
INSERT INTO materia (nombre) VALUES ('INGLES I');
INSERT INTO materia (nombre) VALUES ('INGLES II');
INSERT INTO materia (nombre) VALUES ('INFORMATICA I');
INSERT INTO materia (nombre) VALUES ('INFORMATICA II');
INSERT INTO materia (nombre) VALUES ('ADMINISTRACION DE EMPRESAS');
INSERT INTO materia (nombre) VALUES ('BASE DE DATOS');
INSERT INTO materia (nombre) VALUES ('CALCULO NUMERICO');
INSERT INTO materia (nombre) VALUES ('SISTEMA DE REPRESENTACION');
INSERT INTO materia (nombre) VALUES ('INGENIERIA Y SOCIEDAD');
INSERT INTO materia (nombre) VALUES ('PROBABILIDAD Y ESTADISTICA');
INSERT INTO materia (nombre) VALUES ('INGLES III');


CREATE TABLE profesor ( 
	id NUMBER(4,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	apellido VARCHAR2(30 BYTE) NOT NULL, 
	nombre VARCHAR2(30 BYTE) NOT NULL, 
	mail VARCHAR2(40 BYTE) , 
	Fecha_alta DATE,
	foto BLOB 
);

INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Perez','Gustavo','gperez@profesor.utn.edu.ar',TO_DATE('01/04/2000','DD/MM/YYYY'));
INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Sucre','Antonio','asucre@profesor.frh.utn.edu.ar',TO_DATE('01/07/2019','DD/MM/YYYY'));
INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Garcia','Pedro','pgarcia@profesor.frh.utn.edu.ar',TO_DATE('01/04/2021','DD/MM/YYYY'));
INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Fernandez','Luis','lfernandez@profesor.frh.utn.edu.ar',TO_DATE('01/04/2023','DD/MM/YYYY'));
INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Rivadavia','Bernandino','brivadavia@profesor.frh.utn.edu.ar',TO_DATE('01/04/2006','DD/MM/YYYY'));
INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Moreno','Mariano','mmoreno@profesor.frh.utn.edu.ar',TO_DATE('01/07/2010','DD/MM/YYYY'));
INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Urquiza','Justo Jose','jurquiza@profesor.frh.utn.edu.ar',TO_DATE('01/04/2004','DD/MM/YYYY'));
INSERT INTO profesor (APELLIDO,NOMBRE,MAIL,Fecha_alta) VALUES ('Lorca','Federico','floca@profesor.frh.utn.edu.ar',TO_DATE('01/07/2005','DD/MM/YYYY'));

CREATE TABLE curso( 
	id NUMBER(4,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	profesor NUMBER(4,0),
	materia NUMBER(4,0),
	horario VARCHAR2(15),
	aula VARCHAR2(5),
	fecha_inicio DATE,
	observaciones VARCHAR2(60 BYTE)  
);

ALTER TABLE curso ADD FOREIGN KEY (materia) REFERENCES materia(id);
ALTER TABLE curso ADD FOREIGN KEY (profesor) REFERENCES profesor(id);

INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(1,1,'08:30 a 12:30','PP101',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(1,2,'08:30 a 12:30','PV101',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(2,3,'08:30 a 12:30','PP102',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(2,4,'08:30 a 12:30','PV102',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(3,5,'08:30 a 12:30','PP124',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(8,6,'08:30 a 12:30','PN141',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(3,7,'08:30 a 12:30','PP147',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(4,8,'18:30 a 22:30','AB122',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(5,9,'18:30 a 22:30','AB201',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(6,10,'18:30 a 22:30','AB206',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(7,11,'18:30 a 22:30','AB107',TO_DATE('13/03/2023','DD/MM/YYYY'));
INSERT INTO curso(profesor,materia, horario,aula,fecha_inicio) VALUES(8,12,'18:30 a 22:30','AB316',TO_DATE('13/03/2023','DD/MM/YYYY'));

CREATE TABLE matricula( 
	id NUMBER(4,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	curso NUMBER(4,0),
	alumno NUMBER(4,0),
	nota1 NUMBER(2,0),
	nota2 NUMBER(2,0),
	nota1r NUMBER(2,0),
	nota2r NUMBER(2,0),
	notaf NUMBER(2,0),
	promociona CHAR(1)
);

ALTER TABLE matricula ADD FOREIGN KEY (alumno) REFERENCES alumno(legajo);
ALTER TABLE matricula ADD FOREIGN KEY (curso) REFERENCES curso(id);

Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (1,1,2,6,6,null,6,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (2,4,7,8,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (3,6,8,8,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (4,10,6,5,null,6,6,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (1,2,7,7,null,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (2,5,8,7,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (3,7,4,8,2,null,null,'L');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (4,11,8,8,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (1,3,3,10,7,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (2,15,8,8,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (3,8,7,7,null,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (4,12,7,7,null,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (3,9,6,6,null,null,6,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (4,13,9,9,null,null,9,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (4,14,10,10,null,null,10,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (5,1,6,4,null,5,null,'L');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (6,4,6,6,null,null,6,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (8,6,7,7,null,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (10,10,7,7,null,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (12,2,7,7,null,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (6,5,10,10,null,null,10,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (8,7,6,6,null,null,6,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (10,11,8,8,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (12,3,6,6,null,null,6,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (6,15,9,9,null,null,9,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (8,8,6,9,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (4,12,4,2,2,3,null,'R');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (3,9,7,7,null,null,7,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (10,13,8,8,null,null,8,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (10,14,9,9,null,null,9,'P');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (11,14,3,2,6,6,null,'R');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (11,1,4,4,2,3,null,'L');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (11,4,7,6,null,null,6,'S');
Insert into MATRICULA (CURSO,ALUMNO,NOTA1,NOTA2,NOTA1R,NOTA2R,NOTAF,PROMOCIONA) values (11,6,8,9,null,null,8,'S');

CREATE TABLE libro (
	isbn VARCHAR2(17 BYTE)  PRIMARY KEY, 
	autor VARCHAR2(40 BYTE) NOT NULL, 
	titulo VARCHAR2(60 BYTE) NOT NULL , 
	precio NUMBER(8,2) , 
	editorial VARCHAR2(40 BYTE) 
);

INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-086-9','AGULHON, MAURICE','CIRCULO BURGUES, EL',3890,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-801-101-1','ALBORNOZ, MARTIN','CUANDO EL ANARQUISMO CAUSABA SENSACION',4390,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-099-9','ALINOVI, MATIAS','HISTORIA UNIVERSAL DE LA INFAMIA CIENTIFICA',3890,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-100-2','ALONSO, DANIEL','DESAFIO DEL CANGREJO, EL',2590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-334-1','ALTAMIRANO, CARLOS','INTELECTUALES',3190,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-801-094-6','ALTAMIRANO, CARLOS','LA INVENCION DE NUESTRA AMÉRICA',4290,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-1220-27-4','ALTAMIRANO, CARLOS','PARA UN PROGRAMA DE HISTORIA INTELECTUAL Y OTROS ENSAYOS',2390,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-189-7','ALTAMIRANO, CARLOS','PERONISMO Y CULTURA DE IZQUIERDA',4990,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-666-3','ALTAMIRANO/ SARLO','ENSAYOS ARGENTINOS',4990,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-1220-91-5','ALZOGARAY, RAUL','ELIXIR DE LA MUERTE, EL',2590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-217-7','ALZOGARAY, RAUL','UNA TUMBA PARA LOS ROMANOV ',2590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-143-9','AMSTER, PABLO','MATEMATICA, MAESTRO!',2590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-1105-92-2','AMSTER, PABLO','MATEMATICAS COMO UNA DE LAS BELLAS ARTES, LAS',2590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-300-6','ANDRADE GAMBOA, J.-CORSO, H.','QUÍ?MICA ESTÁ? ENTRE NOSOTROS, LA',2590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-134-7','ANGENOT, MARC','DISCURSO SOCIAL, EL',4190,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-1220-41-0','ANTELO, RAÚL','MARIA CON MARCEL',6385,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-742-4','APPADURAI, ARJUN','HACER NEGOCIOS CON PALABRAS',4590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-801-127-1','ARBALLO, GUSTAVO','BREVÍ?SIMO CURSO DE DERECHO PARA NO ABOGADOS',6190,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-161-3','ARBISER, ARIEL','JUGADOR CIENTÍ?FICO, EL',21590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-1220-79-3','ARGIBAY, PABLO','CORTAR Y PEGAR',7390,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-845-2','CARNOVALE, VERA','COMBATIENTES, LOS (EDICION 2018)',5690,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-550-5','CAROZZI, MARIA JULIA','AQUÍ? SE BAILA EL TANGO','5890','Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-801-211-7','CARRERA, SARALEGUI y otros','ENTRA UNA PACIENTE, SALE UNA DENUNCIA',13490,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-355-6','CASTILLO, HECTOR','SIMPLEMENTE SANGRE',2590,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-874-2','CASTRO, EDGARDO','DICCIONARIO FOUCAULT (EDICION DEFINITIVA)',9990,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-582-6','DUBET, FRANÇOIS','POR QUÉ PREFERIMOS LA DESIGUALDAD?',3790,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-163-7','DUBET, FRANÇOIS','REPENSAR LA JUSTICIA SOCIAL',12890,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-158-3','DUCROT, TODOROV','DICCIONARIO ENCICLOPEDICO DE LAS CIENCIAS DEL LENGUAJE','7690','Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-603-8','DUFF, ANTONY','SOBRE EL CASTIGO',8690,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-436-2','DUJOVNE, ALEJANDRO','UNA HISTORIA DEL LIBRO JUDÍ?O',4990,'Siglo XXI Editores Argentina');
INSERT INTO libro (isbn,autor,titulo,precio,editorial) VALUES ('978-987-629-240-5','DWORKIN, RONALD','UNA CUESTIÓN DE PRINCIPIOS',7990,'Siglo XXI Editores Argentina');

CREATE TABLE categoria (
    codigo NUMBER(4) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(40) NOT NULL,
    sueldo NUMBER(8,2)
);

INSERT INTO categoria (descripcion,sueldo) VALUES ('Titular',82000);
INSERT INTO categoria (descripcion,sueldo) VALUES ('Adjunto',58000);
INSERT INTO categoria (descripcion,sueldo) VALUES ('Jefe de Trabajos Practicos',46000);
INSERT INTO categoria (descripcion,sueldo) VALUES ('Ayudante de Primera',35500);
INSERT INTO categoria (descripcion,sueldo) VALUES ('Ayudante de Segunda',28500);
INSERT INTO categoria (descripcion,sueldo) VALUES ('Asistente',19500);

CREATE TABLE cat_doc (
    categoria NUMBER(4),
    docente NUMBER(4),
    curso NUMBER(4),
    desde DATE,
    hasta DATE
);

ALTER TABLE cat_doc ADD FOREIGN KEY (categoria) REFERENCES categoria(codigo);
ALTER TABLE cat_doc ADD FOREIGN KEY (docente) REFERENCES profesor(id);
ALTER TABLE cat_doc ADD FOREIGN KEY (curso) REFERENCES curso(id);

Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,1,1,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,1,2,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,2,3,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,2,4,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,3,5,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,3,7,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,4,8,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,5,9,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,6,10,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,7,11,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,8,6,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (1,8,12,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,1,3,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,1,4,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,1,7,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,2,11,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,6,12,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,7,8,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,8,9,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (2,8,10,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,2,1,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,2,2,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,3,3,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,3,8,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,3,10,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,4,6,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,4,7,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,4,9,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,6,11,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,7,5,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,7,10,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));
Insert into CAT_DOC (CATEGORIA,DOCENTE,CURSO,DESDE,HASTA) values (3,7,12,to_date('13/03/2023','DD/MM/RRRR'),to_date('08/07/2023','DD/MM/RRRR'));